{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-data
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    app.kubernetes.io/name: {{ .Values.labels.app }}
    app.kubernetes.io/part-of: {{ .Values.labels.app }}
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataDirSize | quote }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  volumeMode: {{ .Values.persistence.volumeMode | quote }}
  {{- end }}
