cluster-configs:
    secrets:
        db:          # update the postgres db credentials
            username: naljaluatuser
            password: naljaluat123  # must be more than 8 characters
            flywayUsername: naljaluatuser
            flywayPassword: naljaluat123  # must be more than 8 characters
        egov-notification-sms: # To work sms notification service add the sms provider details
            username: demo
            password: demo
        egov-filestore:   # To work Filestore service add the IAM user details which has access on the filestore s3 bucket.
            aws-key: aswedfghew
            aws-secret-key: xdefghgdxc
        egov-location:  # To work Location service add your gmap key
            gmapskey: AIzaSyAQOd09-sdfegv
        egov-pg-service:    # To work pg service add your respective bank details
            axis-merchant-id: demo
            axis-merchant-secret-key: demo
            axis-merchant-user: demo
            axis-merchant-pwd: demo
            axis-merchant-access-code: demo
            payu-merchant-key: demo
            payu-merchant-salt: demo
        pgadmin:  # To work pgadmin service add details
            admin-email: demo@demo.com
            admin-password:  demo
            read-email: demo@demo.com
            read-password: demo
        egov-enc-service:  # To work egov-enc service add the details
            master-password: demo
            master-salt: q7.fr.cr
            master-initialvector: 9J&asfgrU-H2
        egov-notification-mail:  # To work mail notification service add respective mail details
            mailsenderusername: demo@demo
            mailsenderpassword: demo
        git-sync:   # To clone the config and mdms repos, Create github user and add your ssh private key below. This private should have access to config and mdms repo.  
            ssh: |
                -----BEGIN RSA PRIVATE KEY-----
                MIIEpQIBAAKCAQEAuv4OIg3amKjdjZa0yMKFFNmCdW5SPZoDtuJJ82aG2MBGa2jD
                IjkVlVHnlm/qw8AUYhx+Oi9xEhwTnn/+vem/UZJA0Sfq6LMJo5Y0zwoKjPEK14Sh
                nPM8ntlBUha1Fo23G01G8gKBtxZU40XdKnPdH/V6XqB3XbPBnrWg1FuD7kaoEHIH
                DLm5sx9+JDkZUNC7MJxkIGBCEfQCU+oia9pypmKoyUwuLdCoB84o1mJl44ytDJ3S
                dS6rIX9oPj8MMYH+uQMe+0Z+JOWON8WGRFo14++ms2/91SBccZNqim3D/b5daWMZ
                MdWLyphB6yghkbIOUPrKPMPoLRUKeJwC7re1UwIDAQABAoIBAQC0fiPwNQUqU90/
                HRg1rKU+gdFOPoW9lls9fWG6Qt2ofLe8V6v67bTqo9txt2eZOV+zcCNbUI3I2DcL
                yCqA8A5O02gjO2+g26hTMdqZeezDLKu1af2BfLun7LcDYI29Tl9PSCFR2p+QtUqM
                8dPQdXQctBtBGYz+clNTOagbMpa/N+fxZDTQU9iZTG9FYb1WA5l9eaa2gOnISgg6
                dM+5lmymhxo0gyMJKxvU+HJpDo8kKNnxpN8/TRpABIuTXFNsSXBHOlS4prlbJ5jV
                Xpv3V/Ho4xGkMepY4Jj94T+Cxlz3LQlh17At6JUVNKq44k/0fsqhhAyWJ+njmSOR
                IGUew3IJAoGBAN6t24/qD3d/jIzXpMA5k248XK3/+d0YzkcwcrYMMBZmvoNomy+E
                P34lA45UFppuhnYAaqQzzGXW+lsd5XlqQL5dJeR8xV6CVaolEGNaxR4a3HknFWBX
                A2iV7bx7FKcx/j5dK1UI4nNhwNL3xRbV1UKTevT9lzVrpMOj2VnCjOfXAoGBANb5
                JoANcdqUxngIJanjIeW13r1sI20Io7Yor9DGSPa2lEqgYzMqP5Q6lTAEmtyFEfFA
                60bPnw5mKRu+df7LZTeyJQtP28kFShIQ0vCquApf9kTjsvOpxElYi1dmh65CByQt
                /AjaWC1/oWE95sekTX8H5eTuenE05jex3VED4/7lAoGBAL5AOlv99VL6peHbiEY3
                qu+/IMwE7LzrKaqHCSrixN8Oz2zEnfn9+qVTCHO9AkbVcYo2FubN3q+P+fyJUXrn
                vgMm4G4T8CksH/arjhHlBo8PEhlsvAXAsgfUOPcVDXM/8mHkBlazrY45EZ7t0/UL
                oxYrnRzd4SfiHTaNsfDPmMWnAoGBAK2poseJlPNegqKO+lYuzcBzVtgxVsELXK2Y
                WsfOlzzvLAbJYLoBpFELrl+XKL+CpIb/ydFvgm+waf8mss295CvFNxXXUpcnNbo4
                ax/O2lRPR3RJedRLzezuocpeYreMUZaRq2w/b0J6O5WB20BmY9B+QeLaIIH5mQ1f
                G4oKGZJdAoGAbouHZZ/tCpOUTjcoFbObbS74omVCK3XpPyCxxIsrJkkY5zcn4UA9
                HsVxIqDc0P/TCOFWzXVdeexsVk/ukKL6MNbCCzUNq2D8GNTwvqxunyap5v425PbV
                sdiWM/rGWwm91IFAC2N5rpa390GAj4j/s3Qp6BOpk1E8x4ocsOjbd9s=
                -----END RSA PRIVATE KEY-----
            known-hosts: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
        kibana:    # Add Kibana details
            namespace: es-cluster
            credentials: demo
        egov-si-microservice:  # Add finance service details
            si-microservice-user: demo
            si-microservice-password: demo
            mail-sender-password: demo
        egov-edcr-notification:  # Add edcr service details
            edcr-mail-username: demo@demo.com
            edcr-mail-password: demo
            edcr-sms-username: demo
            edcr-sms-password: demo
        chatbot:     # Add chatbot details
            valuefirst-username: demo
            valuefirst-password: demo
        egov-user-chatbot:  # Add user chatbot details
            citizen-login-password-otp-fixed-value: "546941"
        oauth2-proxy:   # To work oauth2-proxy service, create and add your github OAuth Apps details
            clientID: 1f475e21f66fc9476d6d
            clientSecret: 204f7be4abd65d03f769da4d78d14a825163cc87
            cookieSecret: QVbnq0L8npoyfxZs96wtBg==
