# Common Labels
labels:
  app: "egov-accesscontrol"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "access"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "egov-accesscontrol"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/access/health"
  readinessProbePath: "/access/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx384m -Xms256m"
memory_limits: 512Mi
java-args: ""

# Additional Container Envs
env: |
  {{- if and (.Values.global.context.path) (has .Values.name .Values.global.context.list) }}
  - name: SERVER_CONTEXTPATH
    value: /{{ .Values.global.context.path }}/{{ .Values.ingress.context }}
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /{{ .Values.global.context.path }}/{{ .Values.ingress.context }}
  {{- else }}
  - name: SERVER_CONTEXTPATH
    value: /{{ .Values.ingress.context }}
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /{{ .Values.ingress.context }}
  {{- end }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_PATH
    value: "mdms-v2/v1/_search"
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"         
