
{{- with index .Values "cluster-configs" "secrets" "egov-filestore" }}
{{- if index . "awssecretkey" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  awskey: {{ index . "awskey" | b64enc | quote }}
  awssecretkey: {{ index . "awssecretkey"  | b64enc | quote }}
{{- end }}
{{- end }}