{{- with index .Values "cluster-configs" "secrets" "firebase-secrets" }}
{{- if index . "apiKey" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  apiKey: {{ index . "apiKey" | b64enc | quote }}
  appId: {{ index . "appId"  | b64enc | quote }}
  messagingSenderId: {{ index . "messagingSenderId" | b64enc | quote }}
  projectId: {{ index . "projectId"  | b64enc | quote }}
  authDomain: {{ index . "authDomain" | b64enc | quote }}
  storageBucket: {{ index . "storageBucket"  | b64enc | quote }}
  measurementId: {{ index . "measurementId" | b64enc | quote }}
{{- end }}
{{- end }}
