{{- with index .Values "cluster-configs" "secrets" "kafka-kraft" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  kraft-cluster-id: {{ index $.Values "cluster-configs" "secrets" "kafka-kraft" "kraft-cluster-id" | b64enc | quote }}
{{- end }}