# Common Labels
labels:
  app: "ifix-reference-adapter-cron"
  group: "ifix-reference-adapter-cron"

cron:
  schedule: "0 0/1 * * *"

# Container Configs
image:
  repository: "byrnedo/alpine-curl"
  tag: "latest"
args: 
- http://ifix-reference-adapter.egov:8080/ifix-reference-adapter/events/v1/_push
