{{- if .Values.master.ingress.enabled }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: {{ .Values.master.ingress.apiVersion }}
{{- end }}
kind: Ingress
metadata:
  name: {{ template "jenkins.fullname" . }}
  namespace: {{ template "jenkins.namespace" . }}
  labels:
{{- include "common.labels" . | nindent 4 }}
{{- if .Values.master.ingress.annotations }}
  annotations:
{{ toYaml .Values.master.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
{{- if (.Values.master.ingress.paths) }}
{{ tpl (toYaml .Values.master.ingress.paths | indent 6) . }}
{{- else }}
      - backend:
          service:
            name: {{ template "jenkins.fullname" . }}
            port:
              number: {{ .Values.master.servicePort }}
{{ if .Values.master.jenkinsUriPrefix }}
        path: {{ .Values.master.jenkinsUriPrefix }}
{{- else }}
        path: {{ .Values.master.ingress.path }}
{{- end }}
{{- if .Values.master.ingress.pathType }}
        pathType: {{ .Values.master.ingress.pathType }}
{{- else }}
        pathType: ImplementationSpecific
{{- end }}
{{- end }}
  tls:
  - hosts:
    - {{ .Values.global.domain }}
    secretName: {{ .Values.global.domain }}-tls-certs
{{- end }}