# Common Labels
labels:
  app: "egov-url-shortening"
  group: "egov"

# Ingress Configs
ingress:
  enabled: true
  zuul: false
  context: "eus"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov-url-shortening_schema"
    image:
      repository: "egov-url-shortening-db"

# Container Configs
image:
  repository: "egov-url-shortening"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/eus/health"
  readinessProbePath: "/eus/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx384m -Xms256m"
memory_limits: 512Mi
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  {{- if and (.Values.global.context.path) (has .Values.name .Values.global.context.list) }}
  - name: SERVER_CONTEXT_PATH
    value: /{{ .Values.global.context.path }}/{{ .Values.ingress.context }}
  - name: SERVER_CONTEXT_PATH
    value: /{{ .Values.global.context.path }}/{{ .Values.ingress.context }}
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /{{ .Values.global.context.path }}/{{ .Values.ingress.context }}
  {{- else }}
  - name: SERVER_CONTEXT_PATH
    value: /{{ .Values.ingress.context }}
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /{{ .Values.ingress.context }}
  {{- end }}
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: HOST_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
