{{- define "common.service" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.name" . }}
  {{- if .Values.global.namespace }}
  {{- if or (eq .Values.namespace "backbone") (eq .Values.namespace "cert-manager") (eq .Values.namespace "es-cluster") (eq .Values.namespace "es-cluster-infra") (eq .Values.namespace "kafka-cluster") (eq .Values.namespace "kafka-kraft") (eq .Values.namespace "monitoring") (eq .Values.namespace "playground") }}
  namespace: {{ .Values.namespace }}
  {{- else }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
  {{- else }}
  namespace: {{ .Values.namespace }}
  {{- end }} 
  annotations: 
{{- if .Values.metrics }}   
    prometheus.io/path: {{ .Values.metrics.path | quote }}
    prometheus.io/port: {{ .Values.metrics.port | quote }}
    prometheus.io/scrape: "true"  
{{- end }}
{{- if .Values.ingress.zuul }}
  {{- if and (.Values.global.context.path) (has .Values.name .Values.global.context.list) }}
    zuul/route-path: {{ .Values.global.context.path }}/{{ .Values.ingress.context }}
  {{- else }}
    zuul/route-path: {{ .Values.ingress.context }}
  {{- end }}
{{- end }}
{{- if and .Values.service .Values.service.additionalAnnotations}}                                   
  {{- tpl  .Values.service.additionalAnnotations . | nindent 4 }}
{{- end }} 
  labels:
{{- include "common.labels" . | nindent 4 }}   
spec:
  selector: 
{{- include "common.labels" . | nindent 4 }}    
  ports:
  - name: http
    port: {{ .Values.httpPort }}
    targetPort: {{ .Values.httpPort }}  
{{- end -}}