# Common Labels
labels:
  app: "mdms-read-cronjob"
  group: "mdms-read-cronjob"

cron:
  schedule: "30 11 * * *"

# Container Configs
image:
  repository: "api-cronjob"
  tag: "ISNE-291-naljalcustomisation"

command: 
  - "python3"
  - "cronJobAPIConfig.py"
args: 
  - "dailyevening"

# Additional Container Envs
env: |
  - name: JOB_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name                    
resources: |
  requests: {}
  
    
