apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  {{- if .Values.global.namespace }}
  {{- if or (eq .Values.namespace "backbone") (eq .Values.namespace "cert-manager") (eq .Values.namespace "es-cluster") (eq .Values.namespace "es-cluster-infra") (eq .Values.namespace "kafka-cluster") (eq .Values.namespace "kafka-kraft") (eq .Values.namespace "monitoring") (eq .Values.namespace "playground") }}
  namespace: {{ .Values.namespace }}
  {{- else }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
  {{- else }}
  namespace: {{ .Values.namespace }}
  {{- end }} 
spec:
  externalName: {{ .Values.externalName }}
  ports:
  - port: {{ .Values.httpPort }}
    protocol: TCP
    targetPort: {{ .Values.httpPort }}
  sessionAffinity: None
  type: {{ .Values.type }}