repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: jaegertracing
  url: https://jaegertracing.github.io/helm-charts
- name: kafka-ui
  url: https://provectus.github.io/kafka-ui-charts
- name: apm-server
  url: https://helm.elastic.co
- name: apm-attacher
  url: https://helm.elastic.co

values:
  - namespace: monitoring
  - ../environments/env.yaml
  - ../environments/env-secrets.yaml

releases:
- name: loki-stack
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: grafana/loki-stack
  version: 2.10.1
  values:
  - ./values/loki-stack.yaml

- name: kube-prometheus-stack
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: prometheus-community/kube-prometheus-stack
  version: 56.6.2
  disableValidation: true
  values:
  - ./values/prometheus.yaml
  - alertmanager:
      enabled: {{ .Values.prometheus.alertmanager.enabled }}
  {{- if .Values.prometheus.alertmanager.enabled }}
  - alertmanager:
      config: {{ index .Values "cluster-configs" "secrets" "alertmanager" "config" | toYaml | nindent 8 }}
  {{- end }}

- name: jaeger
  installed: false
  namespace: es-cluster
  chart: jaegertracing/jaeger
  version: 0.35.0
  values:
  - ./values/jaeger.yaml
  - storage:
      elasticsearch:
        password: {{ .Values.secrets.elasticsearch.password }}
  set:
    - name: query.ingress.hosts[0]
      value: "{{ .Values.global.domain }}"

- name: grafana
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: grafana/grafana
  version: 7.3.0
  values:
  - ./values/grafana.yaml
  - envRenderSecret:
      GF_AUTH_GITHUB_YAMLAPPLICATIONCONFIG_AUTH_OAUTH2_CLIENT_GITHUB_CLIENTID: {{ .Values.secrets.oauth2.clientID }}
      GF_AUTH_GITHUB_CLIENT_SECRET: {{ .Values.secrets.oauth2.clientSecret }}
  set:
    - name: ingress.hosts[0]
      value: "{{ .Values.global.domain }}"
    - name: ingress.tls[0].hosts[0]
      value: {{ .Values.global.domain | quote }}

- name: blackbox
  installed: false
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: prometheus-community/prometheus-blackbox-exporter
  version: 8.2.0
  values:
  - ./values/blackbox-exporter.yaml     

- name: kafka-ui
  installed: true
  namespace: backbone
  chart: kafka-ui/kafka-ui
  version: 0.7.6
  values:
  - ./values/kafka-ui.yaml  

- name: apm-server
  installed: true
  namespace: es-cluster
  chart: elastic/apm-server
  version: 8.5.1
  values:
  - ./values/apm-server.yaml

- name: apm-attacher
  installed: true
  namespace: es-cluster
  chart: elastic/apm-attacher
  version: 1.0.0
  values:
  - ./values/apm-attacher.yaml