namespace: playground 

# Common Labels
labels:
  app: "playground"
  group: "playground"

# Container Configs
image:
  pullPolicy: IfNotPresent  
  repository: playground 
  tag: "mongo-v2"
replicas: "1"
